// Generated by gencpp from file myworkcell_core/PlanCartesianPath.msg
// DO NOT EDIT!


#ifndef MYWORKCELL_CORE_MESSAGE_PLANCARTESIANPATH_H
#define MYWORKCELL_CORE_MESSAGE_PLANCARTESIANPATH_H

#include <ros/service_traits.h>


#include <myworkcell_core/PlanCartesianPathRequest.h>
#include <myworkcell_core/PlanCartesianPathResponse.h>


namespace myworkcell_core
{

struct PlanCartesianPath
{

typedef PlanCartesianPathRequest Request;
typedef PlanCartesianPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanCartesianPath
} // namespace myworkcell_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myworkcell_core::PlanCartesianPath > {
  static const char* value()
  {
    return "e2c94f25791ccda9422dbc6f0a8d45b3";
  }

  static const char* value(const ::myworkcell_core::PlanCartesianPath&) { return value(); }
};

template<>
struct DataType< ::myworkcell_core::PlanCartesianPath > {
  static const char* value()
  {
    return "myworkcell_core/PlanCartesianPath";
  }

  static const char* value(const ::myworkcell_core::PlanCartesianPath&) { return value(); }
};


// service_traits::MD5Sum< ::myworkcell_core::PlanCartesianPathRequest> should match 
// service_traits::MD5Sum< ::myworkcell_core::PlanCartesianPath > 
template<>
struct MD5Sum< ::myworkcell_core::PlanCartesianPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myworkcell_core::PlanCartesianPath >::value();
  }
  static const char* value(const ::myworkcell_core::PlanCartesianPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myworkcell_core::PlanCartesianPathRequest> should match 
// service_traits::DataType< ::myworkcell_core::PlanCartesianPath > 
template<>
struct DataType< ::myworkcell_core::PlanCartesianPathRequest>
{
  static const char* value()
  {
    return DataType< ::myworkcell_core::PlanCartesianPath >::value();
  }
  static const char* value(const ::myworkcell_core::PlanCartesianPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myworkcell_core::PlanCartesianPathResponse> should match 
// service_traits::MD5Sum< ::myworkcell_core::PlanCartesianPath > 
template<>
struct MD5Sum< ::myworkcell_core::PlanCartesianPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myworkcell_core::PlanCartesianPath >::value();
  }
  static const char* value(const ::myworkcell_core::PlanCartesianPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myworkcell_core::PlanCartesianPathResponse> should match 
// service_traits::DataType< ::myworkcell_core::PlanCartesianPath > 
template<>
struct DataType< ::myworkcell_core::PlanCartesianPathResponse>
{
  static const char* value()
  {
    return DataType< ::myworkcell_core::PlanCartesianPath >::value();
  }
  static const char* value(const ::myworkcell_core::PlanCartesianPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYWORKCELL_CORE_MESSAGE_PLANCARTESIANPATH_H
